### ISSUE TITLE
Juste une question (pas d'erreur)

### ISSUE THREAD

**Issue by Vadrieniel** [indilo53/fivem-esx_policejob#1]
Hello, voilà j'ai vu que tu avais mis le job police, je les donc installer, aucun soucis pour le moment. Par contre la question que je me pose c'est pourquoi je n'ai pas de commande ? Je m'explique logiquement tu tape /help tu obtient de l'aide, sauf que moi quand je tape une commande ex: /setjob il affiche /setjob dans le chat.

Petite précision avant j'avais es_roleplay mais les mise a jours tout les ans ma un peut détaché, aujourd'hui j'ai juste la totalité de t'es script + essentialmode ne manque t-il pas quelque chose du coup ?

(Merci pour le hide hud :))

Merci pour ton aide.

**Comment by indilo53** [comment]
Essaie de charger es_admin avant es_extended dans le yml pour voir

**Comment by Vadrieniel** [comment]
Ah voilà de cette façon je peut taper la commande :) Maintenant je doit bien faire "/setjob 3 5" sachant  l'id du job c'est 3 est que le grade c'est 5 ?

Merci :)

**Comment by indilo53** [comment]
Nickel :) Non tu doit faire /setjob  [Ton id sur le serveur] cop [grade]

**Comment by Vadrieniel** [comment]
Super, cela fonctionne parfaitement encore un grand merci à toi, super boulot :)

**Comment by indilo53** [comment]
Merci :)
