### ISSUE TITLE
Amélioration, Fonctionnel, Non fonctionnel

### ISSUE THREAD

**Issue by Vadrieniel** [indilo53/fivem-esx_policejob#2]
Re, donc voilà j'ai tester toute les possibilités avec le job police tout fonctionne parfaitement (même le skin féminin), par contre les amendes comment cela ce passe ? Je met une amende à un amis, ça me dit vous avez mis une amende, mon ami reçois "Vous avez reçu une amende" sauf que cela ne lui retire pas d'argent, il y a aucune option pour payer ou non l'amende, j'ai raté un truc ? ^^

J'ai aussi vu que tu avais mis la possibilité de vérifier la plaque d'un véhicule, tu va intégrer la possibilité de voir le nom du propriétaire du véhicule en question ?

**Comment by indilo53** [comment]
J'ai oublié de préciser le menu amende c'est F7 (et oui il a le choix de payer ou non) et pour la vérification du propriétaire je n'ai encore de solution

**Comment by Vadrieniel** [comment]
Ok je vais tester, pour la solution du propriétaire je vais chercher un peut de mon coter.

Merci de ton aide, je vérifie pour les amendes est je revient te dire quoi :)

**Comment by Vadrieniel** [comment]
C'est fonctionnel en effet :) c'est cool de pouvoir choisir de payé ou non l'amende, d’ailleurs tu à prévu un menu d'interaction ? Afin de pouvoir donner de l'argent ou utiliser des emotes ? Sinon j'ai les idées mais je ne suis pas trop bon en .lua

Par contre je suis pas mauvais en design web donc ci ta besoin d'aide n'hésite pas.

Merci encore :)

**Comment by indilo53** [comment]
Oui c'est prévu dans les es_extended mais je manque de temps pour le moment

**Comment by Vadrieniel** [comment]
Ok pas de soucis :) Merci

**Comment by Armagryzor** [comment]
Super travail , félicitations.

**Comment by indilo53** [comment]
Merci :)

**Comment by Armagryzor** [comment]
Bonjour,

Est-il possible de vous joindre via un teamspeasck ou discord et autres...
Je suis on vas dire " plutôt néophyte " en ce qui concerne la partie
serveur de GTA 5 avec FiveM.

J'aurai souhaitez vous poser deux ou trois questions sans bien évidement
abuser de votre temps.

En vous remercient par avance ,

Cdtl,

Saphir

2017-05-10 21:01 GMT+02:00 indilo53 <notifications@github.com>:
