### ISSUE TITLE
vehicules despawn

### ISSUE THREAD

**Issue by ig0ne** [indilo53/fivem-esx_policejob#3]
Salut petit soucis lors d'une session test avec 5 personnes. plusieurs ont vu leurs véhicule de police disparaitre au bout de 15/20 min alors qu'ils étaient encore dans le véhicule.

**Comment by indilo53** [comment]
Salut, j'ai eu le même souci et je l'ai réglé en baissant le traffic avec msq-sync-and-acl, je l'ai mis à 0.3. Tu peux également faire : 

`Citizen.CreateThread( function()
	while true do
		Wait( 0 )
		SetVehicleDensityMultiplierThisFrame(0.3)
	end
end)`

Le traffic de base est à 1.0

**Comment by ig0ne** [comment]
c'est bien dans msq-sync-and-acl/common/vars.lua? et si oui crowd c'est bien pour les ped?

**Comment by indilo53** [comment]
Exactement

**Comment by ig0ne** [comment]
Merci je test ça dès que j'ai assez de personne sous la main

**Comment by ig0ne** [comment]
ça marche super bien j'ai juste augmenté le rate à 0.5 au lieu de 0.3. je ferme le sujet.
