### ISSUE TITLE
Weapons list

### ISSUE THREAD

**Issue by ig0ne** [indilo53/fivem-esx_policejob#4]
Salut il manque toutes les armes des DLC dont voicie la liste à ajouter à config.lua:
`	--DLC Weapons
	{name = 'WEAPON_SNSPISTOL'},
	{name = 'WEAPON_BOTTLE'},
	{name = 'WEAPON_GUSENBERG'},
	{name = 'WEAPON_SPECIALCARBINE'},
	{name = 'WEAPON_HEAVYPISTOL'},
	{name = 'WEAPON_BULLPUPRIFLE'},
	{name = 'WEAPON_DAGGER'},
	{name = 'WEAPON_VINTAGEPISTOL'},
	{name = 'WEAPON_FIREWORK'},
	{name = 'WEAPON_MUSKET'},
	{name = 'WEAPON_HEAVYSHOTGUN'},
	{name = 'WEAPON_MARKSMANRIFLE'},
	{name = 'WEAPON_HOMINGLAUNCHER'},
	{name = 'WEAPON_PROXMINE'},
	{name = 'WEAPON_SNOWBALL'},
	{name = 'WEAPON_FLAREGUN'},
	{name = 'WEAPON_GARBAGEBAG'},
	{name = 'WEAPON_HANDCUFFS'},
	{name = 'WEAPON_COMBATPDW'},
	{name = 'WEAPON_MARKSMANPISTOL'},
	{name = 'WEAPON_KNUCKLE'},
	{name = 'WEAPON_HATCHET'},
	{name = 'WEAPON_RAILGUN'},
	{name = 'WEAPON_MACHETE'},
	{name = 'WEAPON_MACHINEPISTOL'},
	{name = 'WEAPON_AIR_DEFENCE_GUN'},
	{name = 'WEAPON_SWITCHBLADE'},
	{name = 'WEAPON_REVOLVER'},
	{name = 'WEAPON_DBSHOTGUN'},
	{name = 'WEAPON_COMPACTRIFLE'},
	{name = 'WEAPON_AUTOSHOTGUN'},
	{name = 'WEAPON_BATTLEAXE'},
	{name = 'WEAPON_COMPACTLAUNCHER'},
	{name = 'WEAPON_MINISMG'},
	{name = 'WEAPON_PIPEBOMB'},
	{name = 'WEAPON_POOLCUE'},
	{name = 'WEAPON_WRENCH'}`

**Comment by indilo53** [comment]
Merci, je vais ajouter ca
