### ISSUE TITLE
Compte banquaire police

### ISSUE THREAD

**Issue by ig0ne** [indilo53/fivem-esx_policejob#5]
Salut petite question a tu prévue de faire un compte bancaire commun pour la police que seul le capitaine et les lieutenant puissent accéder? Il serait créditer par les amendes payer par les joueurs et permettrais à la police d'avoir un fond commun pour payer des rançons ou autres.

**Comment by indilo53** [comment]
C'est une bonne idée mais ce n'est pas prévu pour le moment, peux-être dans de futures mises à jours
