### ISSUE TITLE
black_money

### ISSUE THREAD

**Issue by TonTonSheitan** [indilo53/fivem-esx_policejob#6]
FR:
Salut Merci pour ton travail, je ne vais pas faire perdre ton temps trop longtemps :)

-Pour le systeme d'argent sale ya t-il un systeme pour blanchir l'argent ou pour l'instant nous pouvons rien faire avec l'argent sale ?

Merci pour ta réponse.

Cordialement

EN:
Hi thanks for your work, I will not waste your time too long :)

-For the dirty money system is there a system to launder money or for now we can do nothing with dirty money?

Thank you for your answer.

cordially

**Comment by ig0ne** [comment]
Salut il m'a déjà répondu pour ça et donc non pas pour l'instant mais d'ici quelques jours apparemment ;)

**Comment by TonTonSheitan** [comment]
Merci pour ta réponse :) et tu utilise le systeme de faim et soif ??

**Comment by ig0ne** [comment]
Je viens de voir que gabs avait essayer de faire en sorte qu'il soit compatible esx du coup je test tout ca se soir
