### ISSUE TITLE
crochetage et check plate

### ISSUE THREAD

**Issue by ig0ne** [indilo53/fivem-esx_policejob#7]
Salut, le crochetage ne fonctionne pas du tout pour moi. Kyominii à fait une nouvelle release de son script police et je pense que tu pourrais t'en inspirait pour le crochetage et le checkplate. https://github.com/Kyominii/Cops_FiveM/tree/master/police

**Comment by indilo53** [comment]
J'ai fait un commit dit moi si ca fonctionne

**Comment by ig0ne** [comment]
Super c'est fonctionnel manque plus que le checkplate ^^ un grand merci à toi
