### ISSUE TITLE
Amende

### ISSUE THREAD

**Issue by Ryload** [indilo53/fivem-esx_policejob#9]
Salut Indili ! Très bon mod ! Petite question, après avoir mis une amende à une personne, aucun moyen en tant que policier de voir qu'il ne l'a pas payer ou autre ? Car si le joueur n'a aucune pénalité, personne ne va les payer ! Merci d'avance l'ami :)

EDIT : Quel est la dépendance lié a esx_phone d'ailleurs ? Car j'ai un module téléphone fait de A à Z, et je pense l'utiliser à la place

**Comment by Ryload** [comment]
Si c'est possible de discuter via Discord, par écrit ou vocal, je te laisse mon ID : Rylod#8037

**Comment by Lariime** [comment]
Je me permet juste de répondre a une de tes questions ^^ J'espere que indilo53 m'en voudras pas et que je vais pas dire de bêtise.

La dépendance lié a esx_phone c'est le fait que ca te rajoute le numéro de la police dans le répertoire des joueurs. (Indilo53 j’espère ne pas dire de bêtises ^^)

**Comment by indilo53** [comment]
Lariime a raison c'est pour l'appelle police mais tu n'est pas obligé d'utiliser esx_phone. Ca devrais fonctionner quand même. Le choix de payer les amendes est voulu dans le script mais tu peux ajouter une action qui donne la liste des amendes non payées aux policier.

**Comment by Ryload** [comment]
Merci pour tes réponses ! Une dernière question : Comptes-tu scripter l'action qui donne la liste des amendes non payées ? Ca me paraît essentiel, et je t'avoue que je bloque sur quelques points !
